# Файл: netlify.toml
# Путь: "C:\0191\hr-app\hr-app"\netlify.toml

[build]
  # У нас нет шага сборки (как, например, в React), поэтому команда пустая
  command = "# No build command"
  
  # Это самая важная строка. Указывает, что наш сайт - это папка "public"
  publish = "public"
  
  # Явно указываем, где лежат наши бессерверные функции
  functions = "netlify/functions"

# --- НАЧАЛО НОВОГО БЛОКА ---
# Эта секция настраивает нашу функцию-будильник pinger.
[functions.pinger]
  # Расписание в формате CRON.
  # "0 8 * * *" означает "запускать каждый день в 8:00 утра по времени UTC".
  schedule = "0 8 * * *"
# --- КОНЕЦ НОВОГО БЛОКА ---

# Это правило перенаправления теперь будет работать правильно.
# Оно также помогает в работе Single Page Applications (SPA),
# перенаправляя все запросы, которые не являются файлами, на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200